### ISSUE TITLE
Make RT-View work with existing/running nodes 

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-rt-view#109]
Make rt-view speak with the nodes without restarting them.

**Comment by bghughes** [comment]
I second this! Would be a massive help

**Comment by rdlrt** [comment]
I wonder how would that work, unless we're talking about reading stats from EKG / prometheus ports instead, in case of which I would love that too - as its used by other non-IOG tools (grafana / gLiveView) as well and it's part of default config + keeps common interface available 🙂

**Comment by denisshevchenko** [comment]
Yes, it will be done soon. Technically, corresponding PR is already in progress, will be merged next week.

Let me explain the reason of it.

Node uses `TraceForwarderBK` plugin (to send metrics), and RTView uses `TraceAcceptorBK` plugin (to accept metrics). Node establishes the connection with RTView, so this problem is in `TraceForwarderBK`, i.e. it will be fixed in the _node_, not in _RTView_. So please wait for the next node's release. Not `1.23.0`, the _next_ one... :-)

**Comment by PierreManos** [comment]
Hi Denis @denisshevchenko , in mainnet-config.json, must  "ViewMode"  be changed  to "RTView" or can we keep default "SimpleView"?

**Comment by denisshevchenko** [comment]
Technically, it's already fixed in `TraceForwarderBK`: https://github.com/input-output-hk/iohk-monitoring-framework/pull/607. I have to open a new PR which will update `iohk-monitoring` dependency in the node.

**Comment by denisshevchenko** [comment]
It's already fixed, but you have to wait until this PR will be merged in the node: https://github.com/input-output-hk/cardano-node/pull/2180

**Comment by denisshevchenko** [comment]
https://github.com/input-output-hk/cardano-node/pull/2180 is merged.
