### ISSUE TITLE
Inconsistency between blockchain values displayed inside the Peers and Blockchain tabs

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-rt-view#15]
I see that under peers we are displaying the slot no  but under blockchain we are displaying epoch/slot and block no
I think it would be useful (and consistent) to display values that could be easily comparable (in order to easily spot discrepancies), what do you think? One option could be to add the slot no also into the blockchain tab

![image](https://user-images.githubusercontent.com/29144964/94667096-0486b400-0317-11eb-9a83-425940fd497f.png)

![image](https://user-images.githubusercontent.com/29144964/94667115-09e3fe80-0317-11eb-96f1-a60e5aa48d1a.png)

**Comment by denisshevchenko** [comment]
Unfortunately, the number in `Peers` tab is taken from another metric than numbers in `Blockchain` tab. And that metric (which is used for `Peers` tab) contains only slot number. This is the limitation of the structure in `ouroboros-network`, so I only can display this number as it is. So, in order to do it, we must make changes in 3 repositories: `cardano-rt-view`, `cardano-node`, and `ouroboros-network`. Currently, it's too complex task, so I'm closing this issue.

My suggestion is to open it again only if this change (two numbers instead of one in `Peers` tab) will be requested by many RTView users.
