### ISSUE TITLE
rt-view-0.2.0 - no errors shown even there are errors in the node logs

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-rt-view#91]
rt-view is installed on an Ubuntu machine and the web page is opened on a Windows machine. 

![image](https://user-images.githubusercontent.com/29144964/100055831-330f9f80-2e2d-11eb-8ff6-020b1ff9711b.png)

**Comment by denisshevchenko** [comment]
The problem is not on RTView's side: some errors are in a separate namespace, so they are not forwarded by default.

To fix it, their namespace should be added in the node's configuration file, `mapBackends` section. For example, to see DNS-related problems in `Errors` tab, add this:

```
      "cardano.node.DnsResolver": [
        "TraceForwarderBK"
      ],
      "cardano.node.DnsSubscription": [
        "TraceForwarderBK"
      ],
```

in `mapBackends` section.

**Comment by denisshevchenko** [comment]
BTW, I should describe all Error-related namespaces in the documentation.

**Comment by denisshevchenko** [comment]
Later, it will be simplified on the node's side: https://github.com/input-output-hk/cardano-node/issues/2119
